### ISSUE TITLE
Choppy animation

### ISSUE THREAD

**Issue by mythodeia** [Beniamiiin/BSErrorMessageView#5]
First of all thanks for the library. My issue is that when i tap the icon to view the error the leftview appears with a choppy animation. Is this by design?

EDIT:
as i am trying different things now i found that putting this:

```
                             if ( [self.superview isKindOfClass:[UITextField class]] ){
                                 UITextField *textField = (UITextField *)self.superview;
                                 textField.rightView = nil;
                                 textField.rightView = self;
                             }
```

inside the animations block in `errorIconButtonAction` shows a better fade in animation.
Is there any better way to accomplish a nice animation for this?

**Comment by Beniamiiin** [comment]
Hello. Yes, this is bug and it reproduced only on iOS 9. I'm fixed this bug, you can pull new version from develop.

**Comment by mythodeia** [comment]
:+1:  excellent thanks
